/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Counter } from "./Counter";
export type { SimpleStorage } from "./SimpleStorage";
export * as factories from "./factories";
export { Counter__factory } from "./factories/Counter__factory";
export { SimpleStorage__factory } from "./factories/SimpleStorage__factory";
